### PR TITLE
Remove travis configuration file

### PR DESCRIPTION
**Pull request by thaJeztah**
Now that we have GitHub actions running, the travis configuration file should no longer be needed.

follow-up to https://github.com/containerd/console/pull/36 and https://github.com/containerd/console/pull/41

### CODE REVIEW

**Comment by thaJeztah** [comment]
@estesp @cpuguy83 ptal

**Comment by thaJeztah** [comment]
can we tag a release after this is merged?

**Review by estesp — APPROVED** [review]
LGTM

**Review by mikebrow — APPROVED** [review]
LGTM

**Pull request merged**
