### PR TITLE
[do not merge] containerd/console is broken with current golang.org/x/sys

### PR DESCRIPTION
**Pull request by thaJeztah**
As mentioned in https://github.com/docker/buildx/pull/389

> Needed to downgrade sys/unix with replace rule because the new one (that cli requires through moby/term) does not build with moby/moby and containerd/console. https://github.com/golang/sys/commit/6fcdbc0bbc04dcd9e7dc145879ceaf9bf1c6ff03 Moby isn't big issue as could be upgraded/removed but containerd package looks like a chunk of work (especially because on first look package itself does not seem to be implemented correctly)

opening this to discuss (not sure what the right fix/change is yet)

### CODE REVIEW

**Comment by thaJeztah** [comment]
CI doesn't run on macOS, but this is the compile failure;

```
# github.com/containerd/console
./tc_darwin.go:33:31: undefined: unix.SYS_IOCTL
```

https://github.com/containerd/console/blob/af5b089de98183190d0112c46e0405aa783fe054/tc_darwin.go#L33

**Comment by thaJeztah** [comment]
This probably needs similar changes as were made in https://github.com/moby/term/pull/16 @tklauser ?

**Comment by tklauser** [comment]
> This probably needs similar changes as were made in [moby/term#16](https://github.com/moby/term/pull/16) @tklauser ?

Yes, looks like it. I've sent #40 with a fix.

**Comment by thaJeztah** [comment]
let me close this one, now that https://github.com/containerd/console/pull/40 is up

**Pull request closed without merging**
