### PR TITLE
Use IoctlSetPointerInt from golang.org/x/sys/unix

### PR DESCRIPTION
**Pull request by tklauser**
Update the golang.org/x/sys/unix dependency and use unix.IoctlSetPointerInt
instead of manually implementing it. This fixes the build on darwin
where direct syscalls, i.e.  unix.Syscall(SYS_IOCTL, ...) are no longer
allowed and exported as of golang/sys@6fcdbc0

This should unblock #39 /cc @thaJeztah

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thank you! I posted https://github.com/containerd/console/pull/39, and then realised that the changes in moby/term were because of the same issue, but didn't find the time yet to look into it <3

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@crosbymichael @tonistiigi PTAL

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
